#
#  Author: Meir Finkelstine
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/mfinkelstine/Jenkins
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/mfinkelstine
#

---
name: YAML

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - .github/workflows/yaml.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - .github/workflows/yaml.yaml
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check_yaml:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'mfinkelstine'
    name: Check YAML
    uses: mfinkelstine/GitHub-Actions/.github/workflows/yaml.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
